name: Metrics
on:
  schedule: [{cron: "0 * * * *"}] # هر یک ساعت آپدیت میشه
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: hesam0987HHe
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_followup: yes
          plugin_stargazers: yes
