name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # هر ۱۲ ساعت اجرا میشه
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: hesam0987HHe
          outputs: dist/snake.svg
      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
